spring:
  datasource:
    url: 'jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:app}'
    username: '${DB_USER:root}'
    password: '${DB_PASSWORD:root}'
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml