/*
 * This file is generated by jOOQ.
 */
package com.schedlo.postlinker.dao.tables.records;


import com.schedlo.postlinker.dao.tables.Media;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MediaRecord extends UpdatableRecordImpl<MediaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>app.media.is_deleted</code>.
     */
    public void setIsDeleted(Byte value) {
        set(0, value);
    }

    /**
     * Getter for <code>app.media.is_deleted</code>.
     */
    public Byte getIsDeleted() {
        return (Byte) get(0);
    }

    /**
     * Setter for <code>app.media.id</code>.
     */
    public void setId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>app.media.id</code>.
     */
    public Long getId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>app.media.media_type</code>.
     */
    public void setMediaType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>app.media.media_type</code>.
     */
    public String getMediaType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>app.media.media_url</code>.
     */
    public void setMediaUrl(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>app.media.media_url</code>.
     */
    public String getMediaUrl() {
        return (String) get(3);
    }

    /**
     * Setter for <code>app.media.width</code>.
     */
    public void setWidth(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>app.media.width</code>.
     */
    public Integer getWidth() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>app.media.height</code>.
     */
    public void setHeight(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>app.media.height</code>.
     */
    public Integer getHeight() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>app.media.duration</code>.
     */
    public void setDuration(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>app.media.duration</code>.
     */
    public BigDecimal getDuration() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>app.media.file_size</code>.
     */
    public void setFileSize(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>app.media.file_size</code>.
     */
    public Long getFileSize() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>app.media.date_created</code>.
     */
    public void setDateCreated(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>app.media.date_created</code>.
     */
    public LocalDateTime getDateCreated() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>app.media.date_updated</code>.
     */
    public void setDateUpdated(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>app.media.date_updated</code>.
     */
    public LocalDateTime getDateUpdated() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MediaRecord
     */
    public MediaRecord() {
        super(Media.MEDIA);
    }

    /**
     * Create a detached, initialised MediaRecord
     */
    public MediaRecord(Byte isDeleted, Long id, String mediaType, String mediaUrl, Integer width, Integer height, BigDecimal duration, Long fileSize, LocalDateTime dateCreated, LocalDateTime dateUpdated) {
        super(Media.MEDIA);

        setIsDeleted(isDeleted);
        setId(id);
        setMediaType(mediaType);
        setMediaUrl(mediaUrl);
        setWidth(width);
        setHeight(height);
        setDuration(duration);
        setFileSize(fileSize);
        setDateCreated(dateCreated);
        setDateUpdated(dateUpdated);
        resetChangedOnNotNull();
    }
}
