/*
 * This file is generated by jOOQ.
 */
package com.schedlo.postlinker.dao.tables.records;


import com.schedlo.postlinker.dao.tables.User;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>app.user.is_deleted</code>.
     */
    public void setIsDeleted(Byte value) {
        set(0, value);
    }

    /**
     * Getter for <code>app.user.is_deleted</code>.
     */
    public Byte getIsDeleted() {
        return (Byte) get(0);
    }

    /**
     * Setter for <code>app.user.id</code>.
     */
    public void setId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>app.user.id</code>.
     */
    public Long getId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>app.user.email</code>.
     */
    public void setEmail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>app.user.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>app.user.date_created</code>.
     */
    public void setDateCreated(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>app.user.date_created</code>.
     */
    public LocalDateTime getDateCreated() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>app.user.date_updated</code>.
     */
    public void setDateUpdated(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>app.user.date_updated</code>.
     */
    public LocalDateTime getDateUpdated() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(Byte isDeleted, Long id, String email, LocalDateTime dateCreated, LocalDateTime dateUpdated) {
        super(User.USER);

        setIsDeleted(isDeleted);
        setId(id);
        setEmail(email);
        setDateCreated(dateCreated);
        setDateUpdated(dateUpdated);
        resetChangedOnNotNull();
    }
}
