/*
 * This file is generated by jOOQ.
 */
package com.schedlo.postlinker.dao.tables;


import com.schedlo.postlinker.dao.App;
import com.schedlo.postlinker.dao.Keys;
import com.schedlo.postlinker.dao.tables.PostMedia.PostMediaPath;
import com.schedlo.postlinker.dao.tables.User.UserPath;
import com.schedlo.postlinker.dao.tables.records.PostRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Post extends TableImpl<PostRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>app.post</code>
     */
    public static final Post POST = new Post();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PostRecord> getRecordType() {
        return PostRecord.class;
    }

    /**
     * The column <code>app.post.is_deleted</code>.
     */
    public final TableField<PostRecord, Byte> IS_DELETED = createField(DSL.name("is_deleted"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>app.post.id</code>.
     */
    public final TableField<PostRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>app.post.user_id</code>.
     */
    public final TableField<PostRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>app.post.media_id</code>.
     */
    public final TableField<PostRecord, Long> MEDIA_ID = createField(DSL.name("media_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>app.post.message</code>.
     */
    public final TableField<PostRecord, String> MESSAGE = createField(DSL.name("message"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>app.post.date_created</code>.
     */
    public final TableField<PostRecord, LocalDateTime> DATE_CREATED = createField(DSL.name("date_created"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>app.post.date_updated</code>.
     */
    public final TableField<PostRecord, LocalDateTime> DATE_UPDATED = createField(DSL.name("date_updated"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private Post(Name alias, Table<PostRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Post(Name alias, Table<PostRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>app.post</code> table reference
     */
    public Post(String alias) {
        this(DSL.name(alias), POST);
    }

    /**
     * Create an aliased <code>app.post</code> table reference
     */
    public Post(Name alias) {
        this(alias, POST);
    }

    /**
     * Create a <code>app.post</code> table reference
     */
    public Post() {
        this(DSL.name("post"), null);
    }

    public <O extends Record> Post(Table<O> path, ForeignKey<O, PostRecord> childPath, InverseForeignKey<O, PostRecord> parentPath) {
        super(path, childPath, parentPath, POST);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PostPath extends Post implements Path<PostRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PostPath(Table<O> path, ForeignKey<O, PostRecord> childPath, InverseForeignKey<O, PostRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PostPath(Name alias, Table<PostRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PostPath as(String alias) {
            return new PostPath(DSL.name(alias), this);
        }

        @Override
        public PostPath as(Name alias) {
            return new PostPath(alias, this);
        }

        @Override
        public PostPath as(Table<?> alias) {
            return new PostPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : App.APP;
    }

    @Override
    public Identity<PostRecord, Long> getIdentity() {
        return (Identity<PostRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<PostRecord> getPrimaryKey() {
        return Keys.KEY_POST_PRIMARY;
    }

    @Override
    public List<ForeignKey<PostRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_POST_USER_ID);
    }

    private transient UserPath _user;

    /**
     * Get the implicit join path to the <code>app.user</code> table.
     */
    public UserPath user() {
        if (_user == null)
            _user = new UserPath(this, Keys.FK_POST_USER_ID, null);

        return _user;
    }

    private transient PostMediaPath _postMedia;

    /**
     * Get the implicit to-many join path to the <code>app.post_media</code>
     * table
     */
    public PostMediaPath postMedia() {
        if (_postMedia == null)
            _postMedia = new PostMediaPath(this, null, Keys.FK_POST_MEDIA_POST_ID.getInverseKey());

        return _postMedia;
    }

    @Override
    public Post as(String alias) {
        return new Post(DSL.name(alias), this);
    }

    @Override
    public Post as(Name alias) {
        return new Post(alias, this);
    }

    @Override
    public Post as(Table<?> alias) {
        return new Post(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Post rename(String name) {
        return new Post(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Post rename(Name name) {
        return new Post(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Post rename(Table<?> name) {
        return new Post(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Post where(Condition condition) {
        return new Post(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Post where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Post where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Post where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Post where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Post where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Post where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Post where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Post whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Post whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
