/*
 * This file is generated by jOOQ.
 */
package com.schedlo.postlinker.dao;


import com.schedlo.postlinker.dao.tables.Databasechangelog;
import com.schedlo.postlinker.dao.tables.Databasechangeloglock;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class App extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>app</code>
     */
    public static final App APP = new App();

    /**
     * The table <code>app.databasechangelog</code>.
     */
    public final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>app.databasechangeloglock</code>.
     */
    public final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * No further instances allowed
     */
    private App() {
        super("app", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Databasechangelog.DATABASECHANGELOG,
            Databasechangeloglock.DATABASECHANGELOGLOCK
        );
    }
}
