/*
 * This file is generated by jOOQ.
 */
package com.schedlo.postlinker.dao;


import com.schedlo.postlinker.dao.tables.Media;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in app.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index MEDIA_IDX_MEDIA_TYPE_DATE_UPDATED = Internal.createIndex(DSL.name("idx_media_type_date_updated"), Media.MEDIA, new OrderField[] { Media.MEDIA.MEDIA_TYPE, Media.MEDIA.DATE_UPDATED }, false);
}
